# 사이킷런을 이용한 머신러닝

- 파이썬 머신러닝 라이브러리 중 가장 많이 사용되는 라이브러리
- 파이썬스러운 API
    - 파이썬 기반의 다른 머신러닝 패키지도 사이킷런 스타일API 지향
- 머신러닝을 위한 다양한 알고리즘 개발을 위해 편리한 프레임워크와 API 제공
- 오랜 기간 실전 환경에서 검증, 매우 많은 환경에서 사용된 라이브러리

https://scikit-learn.org/stable/

**사이킷런 버전 확인**
**!pip install scikit-learn**

**Anaconda 설치기 기본으로 사이킷런 설치됨**

**설치 명령어 / 이거 난 안됨 ㅠ**
conda install scikit-learnm

**또는 / 난 이게 됨!**
pip install scikit-learn

## 사이킷런을 이용한 붓꽃(iris) 데이터 분류



### 붓꽃 데이터 세트
- sklearn.datasets에 들어 있음
- load_iris()를 통해 로드해서 사용
- 머신러닝 각 분야에서 알고리즘을 측정하기 위한 기본 자료로 다양하게 활용
- 4가지 속성(피처)을 가진 3가지 붓꽃 품종의 50개 샘플 포함

**3가지 붓꽃 품종**
- Setosa
- Versicolor
- Virginica


- 이미지 링크

http://www.lac.inpe.br/~rafael.santos/Docs/CAP394/WholeStory-Iris.html

### 붓꽃의 4가지 속성(피처 (Feature))
- 꽃받침 길이 : Sepal Length
- 꽃받침 너비 : Sepal Width
- 꽃잎의 길이 : Petal Length
- 꽃잎의 너비 : Petal Width

### 분류를 위한 학습 및 예측 프로세스

- 0단계. 데이터 세트 준비
    - 데이터 세트 로딩, 데이터 프레임으로 변환


- 1단계. 데이터 세트 분리
    - 데이터를 학습 데이터와 테스트 데이터로 분리


- 2단계. 모델 학습
    - 학습 데이터를 기반으로 ML 알고리즘을 적용해 모델 학습


- 3단계. 예측 수행
    - 학습된 ML 모델을 이용해 테스트 데이터의 분류(붓꽃 종류) 예측


- 4단계. 모델 성능 평가
    - 예측된 결과값과 테스트 데이터 실제 값 비교하여 ML 모델 성능 평가

용어 정리

피처(Feature) : 데이터 세트 속성
- feature_names : sepal length, sepal with, petal length, petal width
    
레이블(label) :
- 품종 (setosa, versicolor, virginica)
- 학습 : 결정값(주어진 정답)
- 테스트 : 타깃값(target)(예측해야 할 값)
- target(숫자) : 0, 1, 2
- target_names : setosa, versicolor, virginica
- 레이블 = 결정값 = 타겟값

**붓꽃 예측을 위한 사이킷런 필요 모듈 로딩**

In [1]:
# from / import
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd

**붓꽃 데이터 예측 프로세스에서 사용하는 함수 및 클래스**


**데이터 세트 로딩**

In [6]:
# 붓꽃 데이터 세트 로딩
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [7]:
# iris.data : Iris 데이터 세트에서 
# 피처(feature)만으로 된 데이터를 numpy로 가지고 있음
iris_data = iris.data
iris_data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [8]:
# iris.target은 붓꽃 데이터 세트에서 
# 레이블(결정 값) 데이터를 numpy로 가지고 있음 (숫자)
# 레이블 = 결정값 = 정답(품종을 숫자로 표현)
iris_label = iris.target
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
# keys
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [12]:
# feagure
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [14]:
# target
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [15]:
# 붓꽃 데이터 DataFrame으로 변환 
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [17]:
iris_df['label'] = iris_label
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [18]:
# iris_df를 복사하기
iris_df2 = iris_df
iris_df2.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
145      2  
146      2  
147      2  
148      2  
149      2

In [19]:
# 함수 정의
def name(label):
    if label == 0:
        name = 'Setosa'
    elif label == 1:
        name = 'Versicolor'
    else:
        name = 'Virginica'

In [22]:
# 위 함수를 사용해서 'label_name'추가
iris_df2['label_name'] = iris_df2.apply(lambda x : name(x['label']), axis=1)
iris_df2

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label label_name  
0        0       None  
1        0       None  
2        0       None  
3        0       None  
4        0       None  
..     ...        ...  
145      2       None  
146      2       None  
147      2       None  
148      2       None  
149      2       None  

[150 rows x 6 columns]

### 학습 데이터와 테스트 데이터 세트로 분리

**train_test_split() 함수** 사용
* train_test_split(iris_data, iris_label, test_size=0.3, random_state=11)


* train_test_split(피처 데이터 세트, 레이블 데이터 세트, 테스트 데이터 세트 비율, 난수 발생값)
    * 피처 데이터 세트 : 피처(feature)만으로 된 데이터(numpy) [5.1, 3.5, 1.4, 0.2],...
    * 레이블 데이터 세트 : 레이블(결정 값) 데이터(numpy) [0 0 0 ... 1 1 1 .... 2 2 2]  
    * test_size(테스트 데이터 세트 비율) : 전체 데이터 세트 중 테스트 데이터 세트 비율 (0.3)
    * random_state(난수 발생값) : 수행할 때마다 동일한 데이터 세트로 분리하기 위해 시드값 고정 (실습용)

train_test_split() 반환값
* X_train : 학습용 피처 데이터 세트  (feature)
* X_test : 테스트용 피처 데이터 세트  (feature)
* y_train : 학습용 레이블 데이터 세트 (target)
* y_test : 테스트용 레이블 데이터 세트 (target)

* feature : 대문자 X_
* label(target) : 소문자 y_

In [23]:
from sklearn.model_selection import train_test_split
#학습 데이터와 테스트 데이터 세트로 분리
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.3, random_state=11)

In [24]:
# 학습용 피처 데이터 세트
X_train[:10]

array([[5.1, 2.5, 3. , 1.1],
       [6.6, 2.9, 4.6, 1.3],
       [5. , 3.2, 1.2, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5.1, 3.8, 1.6, 0.2],
       [6.8, 3.2, 5.9, 2.3],
       [6.9, 3.1, 5.1, 2.3],
       [5.9, 3. , 4.2, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.7, 3.1, 4.7, 1.5]])

In [25]:
# 테스트용 피처 데이터 세트
X_test[:10]

array([[6.8, 3. , 5.5, 2.1],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.8, 5.1, 1.5],
       [6.3, 3.3, 4.7, 1.6],
       [6.4, 2.7, 5.3, 1.9],
       [4.9, 3.1, 1.5, 0.1],
       [6.7, 3.1, 4.4, 1.4],
       [5.7, 4.4, 1.5, 0.4],
       [4.8, 3.1, 1.6, 0.2],
       [6.1, 2.9, 4.7, 1.4]])

In [26]:
# 학습용 레이블 데이터 세트
y_train[:5]

array([1, 1, 0, 2, 0])

In [27]:
# 테스트용 레이블 데이터 세트
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0, 2, 2, 1, 0, 1, 1, 2, 0, 1,
       2])

### 학습 데이터 세트로 학습(Train) 수행

ML 알고리즘으로 의사결정 트리 알고리즘을 이용해서 학습과 예측 수행  
DecisionTreeClassifier 클래스의 fit()/predict() 메소드 사용  

In [28]:
from sklearn.tree import DecisionTreeClassifier
# DecisionTreeClassifier 객체 생성 

df_clf = DecisionTreeClassifier()

# 학습 수행 : fit()
df_clf.fit(X_train, y_train)

# 학습용 피처 데이터, 학습용 레이블(정답) 데이터

DecisionTreeClassifier()

### 테스트 데이터 세트로 예측(Predict) 수행

In [29]:
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행. 
pred = df_clf.predict(X_test)
# 테스트용 피처 데이터

In [30]:
# 예측
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0, 2, 2, 2, 0, 2, 1, 2, 0, 1,
       2])

In [31]:
# 정답
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0, 2, 2, 1, 0, 1, 1, 2, 0, 1,
       2])

### 예측 정확도(accuracy) 평가

In [34]:
from sklearn.metrics import accuracy_score
# accuracy_score(정답, 예측)
accuracy_score(y_test, pred)

0.9111111111111111